import random

# random_integer = []
# while True:
#     r1 = random.randint(1,60)
#     random_integer.append(r1)
#     if len(random_integer) == 60:
#         break
#     print(r1)

# 1- Write a Python program to generate a random integer number in range [5-10]
print("Random integer number in range [5-10]:", random.randint(5, 10))

# 2- Write a Python program to generate a random float number in range [5-10]
print("Random float number in range [5-10]:", random.uniform(5, 10))

# 3- Write a Python program to initialize the random number generator by the seed 5
random.seed(5)
print("Random float number generated by seed 5:", random.uniform(5, 10))
print("Random integer number generated by seed 5:", random.randint(5, 10))
